/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    After: typeof import('./src/components/after.vue')['default']
    Clinica: typeof import('./src/components/clinica.vue')['default']
    ComoChegar: typeof import('./src/components/comoChegar.vue')['default']
    Compteste: typeof import('./src/components/compteste.vue')['default']
    Contatos: typeof import('./src/components/contatos.vue')['default']
    Navfooter: typeof import('./src/components/navfooter.vue')['default']
    NavHeader: typeof import('./src/components/navHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Servicos: typeof import('./src/components/servicos.vue')['default']
  }
}
